### ISSUE TITLE
ERROR:index list out of range

### ISSUE THREAD

**Issue by mas160** [ucdavis-bioinformatics/proc10xG#3]
Hi,

I am trying to use your pipeline to trim the barcodes on my 10x generated raw reads but I am getting the following error:
PROCESS NOTE    Finished reading in barcode whitelist
PROCESS FILES   L4R1.fastq,L4R2.fastq
PROCESS ERROR:[TwoReadIlluminaRun] Error reading next read
Traceback (most recent call last):
  File "./proc10xG/process_10xReads.py", line 463, in main
    fragment = iterator.next_raw()
  File "./proc10xG/process_10xReads.py", line 252, in next_raw
    rbc = (id1.split()[1]).split(':')[3]
IndexError: list index out of range
PROCESS ERROR   An unknown fatal error was encountered.
how can this be solve?

Hoping to hear from you soon.

thanks,

**Comment by mdoliv** [comment]
I think I've found the issue. On line `252` of `process_10xReads.py`, the method tries to do the following operation to the sequence header, assuming the header is in the following format:

`@SRR001666.1 071112_SLXA-EAS1_s_7:5:1:817:345 length=36`

It attempts to grab the part with `071112_SLXA-EAS1_s_7:5:1:817:345`, split it by the ":" (colon) character and get the string at the third index. This is usually fine, but look at the headers for my FASTQ files retrieved from NCBI SRA using `fasterq-dump`:

`@SRR9108936.1 1 length=150`

It doesn't conform to the format the script specifies. For what I understood, what the script wants to get is the second string in this header, which in this case is just the number "1". A possible temporary fix is to go to line 252 and change this:

`rbc = (id1.split()[1]).split(':')[3]`

to this:

`rbc = id1.split()[1]`

Note that this is just a temp fix, something more elegant must be done to account for different header formats.
